---
- name: HANA Start/Stop
  gather_facts: no
  hosts: all
  tasks:
    - name: Start HANA
      become: yes
      become_user: root
      ansible.builtin.script: SAP.py -hu
      tags: start
      - name: Start HANA
      become: yes
      become_user: root
      ansible.builtin.script: SAP.py -hd
      tags: stop
